version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "1706:27017"
    environment:
      MONGO_INITDB_DATABASE: memory_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network

volumes:
  mongodb_data:

networks:
  mongodb_network:
    driver: bridge